server:
    servlet:
        session:
            cookie:
                same-site: none
                http-only: true
                path: /
            timeout: 3600
spring:
    cache:
        port: 8081
    profiles.active: local
    datasource:
        url: >-
            jdbc:mariadb://${database.host}:${database.port}/${database.database}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
        driver-class-name: org.mariadb.jdbc.Driver
        username: '${database.username}'
        password: '${database.password}'
    jpa:
        show_sql: false
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
                dialect: org.hibernate.dialect.MariaDBDialect
                hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                default_batch_fetch_size: '${chunkSize:100}'
                jdbc.batch_size: 20
                order_inserts: true
                order_updates: true
                format_sql: true
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        clientId: '${kakao.apikey}'
                        clientSecret: '${kakao.client-secret}'
                        clientAuthenticationMethod: client_secret_post
                        authorizationGrantType: authorization_code
                        redirectUri: '${kakao.redirectUrl}'
                        scope:
                            - openid
                            - profile_image
                        clientName: Kakao
                provider:
                    kakao:
                        authorizationUri: 'https://kauth.kakao.com/oauth/authorize'
                        tokenUri: 'https://kauth.kakao.com/oauth/token'
                        userInfoUri: 'https://kapi.kakao.com/v2/user/me'
                        userNameAttribute: sub
                        jwkSetUri: 'https://kauth.kakao.com/.well-known/jwks.json'
    application:
        name: Born-to-run
        version: v1.0.0
cors:
    allowed-origins: '${cors.origin}'
    allowed-methods: 'GET,POST,PUT,DELETE,OPTIONS'
    allowed-headers: '*'
    max-age: 3600
app:
    auth:
        tokenExpiry: 3600000
        refreshTokenExpiry: 604800000
adapter:
    discord:
        host: 'https://discord.com'
        webhook-path: '/api/webhooks/${discord.webhook}'
        content-type: application/json
    objectstorage:
        minio:
            node: '${minio.node}'
            access-key: '${minio.access-key}'
            secret-key: '${minio.secret-key}'
            cdn-host: '${cdn.host}'
    redis:
        host: '${redis.host}'
        port: '${redis.port}'
        password: '${redis.password}'
        timeout: 60000

logging:
    file:
        name: logs/btr-api.log
    rolling:
        filename-pattern: 'logs/api/btr-api-%d{yyyy-MM-dd}.log'
    pattern:
        console: '[%d{yyyy-MM-dd HH:mm:ss.SSS}][%thread][%-5level] %logger{50} - %msg%n'
        file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}][%thread][%-5level] %logger{50} - %msg%n'
    level:
        org.hibernate.orm.jdbc.bind: TRACE
